### ISSUE TITLE
issues with Belgiums mortality tables 

### ISSUE THREAD

**Issue by korilium** [JuliaActuary/MortalityTables.jl#130]
When I want to use select with a belgiums mortality table, I get the following error: 
`
ERROR:type UltimateTable has no field select  
`  

I use the following code : 
`
using MortalityTables
mort = MortalityTables.table(897)
mort.select[10]
`

The field ultimate does work for the Belgium tables. 
I have tried to following tables: 
* 898
* 897
* 896
* 895
* 634
* 633
* 30001

**Comment by alecloudenback** [comment]
I'm going to close this issue as it seems the tables are working as provided, but if you want to discuss further please feel free to respond here or in the Discussions tab.
