### ISSUE TITLE
.table() not defined 

### ISSUE THREAD

**Issue by Syker-uk** [JuliaActuary/MortalityTables.jl#97]
I have a few problems with your package; 
1. No help: 
MortalityTables.jl has no docstrings, no help nor methods registered.

2. Althought the tables are accessible with `MortalityTables.tables()`, the method `table()` is not found:
```
using MortalityTables

table = MortalityTables.table("2001 VBT Residual Standard Select and Ultimate - Male Nonsmoker, ANB")
```
```
>> ERROR: UndefVarError: table not defined
```
I installed the library as follow;
```
>> julia:  ]
>> julia (pkg): add MortalityTables
```

**Comment by Syker-uk** [comment]
The official repo has an old version.

**Comment by alecloudenback** [comment]
Hello, yes it seems you may have encountered an old version of the package. For usage, there is:

- Docstrings available interactively (e.g. `?survival`)
- A detailed listed of the available functions and features in the [Docpages](https://juliaactuary.github.io/MortalityTables.jl/stable/)
- A number of examples in the readme on the [repository page](https://github.com/JuliaActuary/MortalityTables.jl).
- An interactive table comparison tool: https://juliaactuary.org/tutorials/mortalitytablecomparison/
- And the package [LifeContingencies.jl](https://github.com/JuliaActuary/LifeContingencies.jl) integrates with and uses MortalityTables.jl

If you have other usage troubles or need help troubleshooting why you might have an older version of the package in your environment, please feel free to respond here.

**Comment by alecloudenback** [comment]
I also double checked that the general registry [has the latest version](https://github.com/JuliaRegistries/General/blob/e4780cfdf23f4c76b5dd6ca8eb046ece0236d138/M/MortalityTables/Versions.toml#L91) so if updating package (e.g. `] up MortalityTables`) does not work for you please feel free to ping this issue again.
